// <auto-generated />
using BarcelonaAPIREST.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarcelonaAPIREST.Migrations
{
    [DbContext(typeof(SglDbContext))]
    partial class SglDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarcelonaAPIREST.Domain.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Escudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 2,
                            Name = "RealMadrid"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Milan"
                        });
                });

            modelBuilder.Entity("BarcelonaAPIREST.Domain.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("Jugadors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipoId = 1,
                            Name = "LamineYamal",
                            Posicion = "ED"
                        },
                        new
                        {
                            Id = 2,
                            EquipoId = 2,
                            Name = "GonzaloGarcia",
                            Posicion = "DC"
                        },
                        new
                        {
                            Id = 3,
                            EquipoId = 3,
                            Name = "RafaelLeao",
                            Posicion = "EI"
                        });
                });

            modelBuilder.Entity("BarcelonaAPIREST.Domain.Jugador", b =>
                {
                    b.HasOne("BarcelonaAPIREST.Domain.Equipo", "Equipo")
                        .WithMany("Jugadors")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("BarcelonaAPIREST.Domain.Equipo", b =>
                {
                    b.Navigation("Jugadors");
                });
#pragma warning restore 612, 618
        }
    }
}
