// <auto-generated />
using BarcelonaAPIREST.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarcelonaAPIREST.Migrations
{
    [DbContext(typeof(SglDbContext))]
    partial class SglDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarcelonaAPIREST.Domain.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Escudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 2,
                            Name = "RealMadrid"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Milan"
                        });
                });

            modelBuilder.Entity("BarcelonaAPIREST.Domain.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dorsal")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("Jugadors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dorsal = 10,
                            EquipoId = 1,
                            Foto = "https://www.fcbarcelona.com/photo-resources/2025/07/09/47ddeac8-9a36-4618-af27-5b1310184370/19-Lamine.jpg?width=1200&height=750",
                            Name = "LamineYamal",
                            Posicion = "ED"
                        },
                        new
                        {
                            Id = 2,
                            Dorsal = 14,
                            EquipoId = 1,
                            Foto = "https://www.fcbarcelona.com/photo-resources/2025/07/28/75f02288-6747-4d91-8a1f-fcbd3857fd1a/Fitxa-14-Blau-Rashford.jpg?width=1680&height=1050",
                            Name = "MarcusRashford",
                            Posicion = "EI"
                        },
                        new
                        {
                            Id = 3,
                            Dorsal = 9,
                            EquipoId = 1,
                            Foto = "https://www.fcbarcelona.com/photo-resources/2025/07/09/e8378527-14fe-4dc7-a0c2-e3cea291a6e2/09-Lewandowski.jpg?width=1680&height=1050",
                            Name = "RobertLewandoski",
                            Posicion = "DC"
                        },
                        new
                        {
                            Id = 4,
                            Dorsal = 11,
                            EquipoId = 1,
                            Foto = "https://www.fcbarcelona.com/photo-resources/2025/07/09/87585699-3a8f-41d4-9912-e63f569f6fd6/11-Raphinha.jpg?width=1680&height=1050",
                            Name = "Raphinha",
                            Posicion = "EI"
                        },
                        new
                        {
                            Id = 5,
                            Dorsal = 13,
                            EquipoId = 1,
                            Foto = "https://www.fcbarcelona.com/photo-resources/2025/07/09/3337817d-b39f-4dfa-924b-89994d15eee1/00-Joan_Garcia.jpg?width=1680&height=1050",
                            Name = "JoanGarcia",
                            Posicion = "POR"
                        });
                });

            modelBuilder.Entity("BarcelonaAPIREST.Domain.Jugador", b =>
                {
                    b.HasOne("BarcelonaAPIREST.Domain.Equipo", "Equipo")
                        .WithMany("Jugadors")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("BarcelonaAPIREST.Domain.Equipo", b =>
                {
                    b.Navigation("Jugadors");
                });
#pragma warning restore 612, 618
        }
    }
}
